import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
padding.x = 10
padding.y = 10
opacity = 0.85
decorations = "None"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = false

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 14
